name: whisper

dependencies:
  # ... existing dependencies ...
  uuid: ^4.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  # ... existing dev_dependencies ...
  build_runner: ^2.4.6
  json_serializable: ^6.7.1 